SLING-8262 -  Add SonarQube analysis to Jenkins jobs
Don't pass the Matcher to withArtifacts it (presumably) is the cause of
java.io.NotSerializableException: java.util.regex.Matcher .